### ISSUE TITLE
Pre-Presentation Checklist

### ISSUE THREAD

**Issue by mxbialostocki** [kahikatea-2019/kidskash#128]
- [ ] Refactor Codebase for unnecessary mentions.

- [x] Refactor Seeds && Migrations for truthy data.

- [x] Rename project.

- [ ] Split presentation into five strong sections, one for each person to present.

- [x] Render currentUser name in Dashboard.
